GameAssistantWeb.Main/Controllers/ProjectController.cs
using GameAssistantWeb.DataAccessLayer.Contracts;
using GameAssistantWeb.BusinessLogic.Contracts;
using GameAssistantWeb.Models.Identity;
using GameAssistantWeb.Repository.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameAssistantWeb.ViewModels.Project;

namespace GameAssistantWeb.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        private readonly IUnitOfWork _uow;
        private readonly IAccountService _accountService;
        private readonly IProjectService _projectService;
        private readonly ILevelService _levelService;
        private readonly IEventService _eventService;
        private readonly IAchievementService _achievementService;

        public ProjectController(IUnitOfWork uow, IRepository<ApplicationUser> applicationUserRepository, IAchievementService achievementService, IEventService eventService, ILevelService levelService, IProjectService projectService, IAccountService accountService)
        {
            _uow = uow;
            _accountService = accountService;
            _achievementService = achievementService;
            _projectService = projectService;
            _levelService = levelService;
            _eventService = eventService;
        }


        [HttpGet]
        public ActionResult Index(int ProjectId)
        {
            if (ShouldRedirect(ProjectId))
                return RedirectToAction("Index", "Home");

            return View();
        }


        [HttpGet]
        public ActionResult Levels(int ProjectId)
        {
            if (ShouldRedirect(ProjectId))
                return RedirectToAction("Index", "Home");

            IEnumerable<LevelViewModel> levels = _levelService.GetLevels(ProjectId);

            return View(levels);
        }

        [HttpGet]
        public PartialViewResult _AddLevelPartial(int ProjectId)
        {
            LevelViewModel model = new LevelViewModel { ProjectId = ProjectId };
            return PartialView("_AddOrEditLevelPartial", model);
        }

        [HttpGet]
        public PartialViewResult _EditLevelPartial(int ProjectId, int LevelId)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            LevelViewModel model = _levelService.GetLevel(LevelId);

            if (model.Project.OwnerId != user.Id)
                model = new LevelViewModel();

            return PartialView("_AddOrEditLevelPartial", model);
        }

        [HttpPost]
        public ActionResult AddOrEditLevel(LevelViewModel model)
        {
            if (ShouldRedirect(model.ProjectId))
                return RedirectToAction("Index", "Home");

            var user = _accountService.GetUserByName(User.Identity.Name);

            if (model.LevelId == 0){
                _levelService.AddLevel(model, user.Id);
                TempData["message"] = "Level successfully added";
            }
            else { 
                _levelService.EditLevel(model, user.Id);
                TempData["message"] = "Level successfully edited";
            }

            return RedirectToAction("Levels", new { ProjectId = model.ProjectId });
        }

        [HttpGet]
        public PartialViewResult _DeleteLevelPartial(int LevelId)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            LevelViewModel model = _levelService.GetLevel(LevelId);

            if (model.Project.OwnerId != user.Id)
                model = new LevelViewModel();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult DeleteLevel(LevelViewModel model)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            _levelService.DeleteLevel(model.LevelId, user.Id);

            TempData["message"] = "Level successfully deleted";
            return RedirectToAction("Levels", new { ProjectId = model.ProjectId });
        }








        [HttpGet]
        public ActionResult Events(int ProjectId)
        {
            if (ShouldRedirect(ProjectId))
                return RedirectToAction("Index", "Home");

            IEnumerable<EventViewModel> events = _eventService.GetEvents(ProjectId);

            return View(events);
        }

        [HttpGet]
        public PartialViewResult _AddEventPartial(int ProjectId)
        {
            EventViewModel model = new EventViewModel { ProjectId = ProjectId };
            return PartialView("_AddOrEditEventPartial", model);
        }

        [HttpGet]
        public PartialViewResult _EditEventPartial(int ProjectId, int EventId)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            EventViewModel model = _eventService.GetEvent(EventId);

            if (model.Project.OwnerId != user.Id)
                model = new EventViewModel();

            return PartialView("_AddOrEditEventPartial", model);
        }

        [HttpPost]
        public ActionResult AddOrEditEvent(EventViewModel model)
        {
            if (ShouldRedirect(model.ProjectId))
                return RedirectToAction("Index", "Home");

            var user = _accountService.GetUserByName(User.Identity.Name);

            if (model.EventId == 0)
            {
                _eventService.AddEvent(model, user.Id);
                TempData["message"] = "Event successfully added";
            }
            else
            {
                _eventService.EditEvent(model, user.Id);
                TempData["message"] = "Event successfully edited";
            }

            return RedirectToAction("Events", new { ProjectId = model.ProjectId });
        }

        [HttpGet]
        public PartialViewResult _DeleteEventPartial(int EventId)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            EventViewModel model = _eventService.GetEvent(EventId);

            if (model.Project.OwnerId != user.Id)
                model = new EventViewModel();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult DeleteEvent(EventViewModel model)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            _eventService.DeleteEvent(model.EventId, user.Id);

            TempData["message"] = "Event successfully deleted";
            return RedirectToAction("Events", new { ProjectId = model.ProjectId });
        }





        [HttpGet]
        public ActionResult Achievements(int ProjectId)
        {
            if (ShouldRedirect(ProjectId))
                return RedirectToAction("Index", "Home");

            IEnumerable<AchievementViewModel> events = _achievementService.GetAchievements(ProjectId);

            return View(events);
        }


        [HttpGet]
        public PartialViewResult _AddAchievementPartial(int ProjectId)
        {
            AchievementViewModel model = _achievementService.CreateAchievementViewModel(ProjectId);
            return PartialView("_AddOrEditAchievementPartial", model);
        }


        [HttpGet]
        public PartialViewResult _EditAchievementPartial(int ProjectId, int AchievementId)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            AchievementViewModel model = _achievementService.GetAchievement(AchievementId, ProjectId);

            if (model.Project.OwnerId != user.Id)
                model = _achievementService.CreateAchievementViewModel(ProjectId);

            return PartialView("_AddOrEditAchievementPartial", model);
        }


        [HttpPost]
        public ActionResult AddOrEditAchievement(AchievementViewModel model)
        {
            if (ShouldRedirect(model.ProjectId))
                return RedirectToAction("Index", "Home");

            var user = _accountService.GetUserByName(User.Identity.Name);

            if (model.AchievementId == 0)
            {
                _achievementService.AddAchievement(model, user.Id);
                TempData["message"] = "Event successfully added";
            }
            else
            {
                _achievementService.EditAchievement(model, user.Id);
                TempData["message"] = "Event successfully edited";
            }

            return RedirectToAction("Achievements", new { ProjectId = model.ProjectId });
        }

        [HttpGet]
        public PartialViewResult _DeleteAchievementPartial(int AchievementId)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            AchievementViewModel model = _achievementService.GetAchievement(AchievementId);

            if (model.Project.OwnerId != user.Id)
                model = new AchievementViewModel();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult DeleteAchievement(AchievementViewModel model)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            _achievementService.DeleteAchievement(model.AchievementId, user.Id);

            TempData["message"] = "Achievement successfully deleted";
            return RedirectToAction("Achievements", new { ProjectId = model.ProjectId });
        }

        public bool ShouldRedirect(int ProjectId)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            var project = _projectService.GetProjectById(ProjectId, user.Id);
            if (project == null)
                return true;
            else
            {
                ViewBag.ProjectName = project.ProjectName;
                ViewBag.ProjectId = project.ProjectId;
                return false;
            }
        }
    }
}

GameAssistantWeb.Main/Controllers/ProjectListController.cs
using GameAssistantWeb.DataAccessLayer.Contracts;
using GameAssistantWeb.Models.Identity;
using GameAssistantWeb.Repository.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using GameAssistantWeb.BusinessLogic.Contracts;
using GameAssistantWeb.Models.Project;
using GameAssistantWeb.ViewModels.Project;

namespace GameAssistantWeb.Controllers
{
    [Authorize]
    public class ProjectListController : Controller
    {
        private readonly IUnitOfWork _uow;
        private readonly IAccountService _accountService;
        private readonly IProjectService _projectService;

        public ProjectListController(IUnitOfWork uow, IRepository<ApplicationUser> applicationUserRepository, IProjectService projectService, IAccountService accountService)
        {
            _uow = uow;
            _accountService = accountService;
            _projectService = projectService;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            IEnumerable<ProjectViewModel> ProjectList = _projectService.GetProjetsByUserId(user.Id);


            return View(ProjectList);
        }

        [HttpGet]
        public PartialViewResult _AddProjectPartial()
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            ProjectViewModel model = new ProjectViewModel();

            return PartialView("_AddOrEditProjectPartial", model);
        }

        [HttpGet]
        public PartialViewResult _EditProjectPartial(int ProjectId)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            ProjectViewModel model = _projectService.GetProjectById(ProjectId, user.Id);

            return PartialView("_AddOrEditProjectPartial", model);
        }

        [HttpPost]
        public ActionResult AddOrEditProject(ProjectViewModel model)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);

            if (model.ProjectId == 0)
                _projectService.AddProject(model, user.Id);
            else
                _projectService.EditProject(model, user.Id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public PartialViewResult _DeleteProjectPartial(int ProjectId)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            ProjectViewModel projectToDelete = _projectService.GetProjectById(ProjectId, user.Id);
            return PartialView(projectToDelete);
        }

        [HttpPost]
        public ActionResult DeleteProject(ProjectViewModel model)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            _projectService.DeleteProject(model.ProjectId, user.Id);

            return RedirectToAction("Index");
        }
    }
}

GameAssistantWeb.Main/Views/ProjectList/Index.cshtml
@model IEnumerable<GameAssistantWeb.ViewModels.Project.ProjectViewModel>
@{
    ViewBag.Title = "Index";
    //Layout = "~/Views/Shared/_ProjectLayout.cshtml";
}

@*<div class="col-sm-3 col-md-2 sidebar">
        <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
            <li><a href="#">Reports</a></li>
            <li><a href="#">Analytics</a></li>
            <li><a href="#">Export</a></li>
        </ul>
        <ul class="nav nav-sidebar">
            <li><a href="">Nav item</a></li>
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
            <li><a href="">More navigation</a></li>
        </ul>
        <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
        </ul>
    </div>*@
<div class="page-header">
    <h1>Project list</h1>
</div>
<div class="well">
    <p>Here you can manage your project list. You are able to create new, edit or delete project.</p>
</div>

@for (int i = 0; i < Model.Count(); i++)
{
    <div class="col-sm-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">@Model.ElementAt(i).ProjectName</h3>
            </div>
            <div class="panel-body">
                <b>Project ID: @Model.ElementAt(i).ProjectId</b><br />
                @Model.ElementAt(i).TrimmedProjectDescription<hr />
                <a href="@Url.Action("Index", "Project", new { ProjectId = Model.ElementAt(i).ProjectId })"><i class="glyphicon glyphicon-stats btn btn-default" title="More"></i></a>
                <i class="glyphicon glyphicon-pencil btn btn-default" title="Edit" data-toggle="modal" data-target="#addProjectModal-@Model.ElementAt(i).ProjectId"></i>
                @{Html.RenderAction("_EditProjectPartial", new { ProjectId = Model.ElementAt(i).ProjectId });}

                <i class="glyphicon glyphicon-remove btn btn-default" title="Delete" data-toggle="modal" data-target="#deleteProjectModal-@Model.ElementAt(i).ProjectId"></i>
                @{Html.RenderAction("_DeleteProjectPartial", new { ProjectId=Model.ElementAt(i).ProjectId });}

            </div>
        </div>
    </div>

}

<div class="col-sm-4">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Add new project</h3>
        </div>
        <div class="panel-body">
            <button type="button" class="btn btn-default  btn-lg btn-block" data-toggle="modal" data-target="#addProjectModal">Add</button>
        </div>
    </div>
</div>

<!-- Modal -->
@{Html.RenderAction("_AddProjectPartial");}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GameAssistantWeb.Main/Views/ProjectList/_AddOrEditProjectPartial.cshtml
@model GameAssistantWeb.ViewModels.Project.ProjectViewModel


@if (Model.ProjectId != 0)
{
    @:<div class="modal fade" id="addProjectModal-@Model.ProjectId" tabindex="-1" role="dialog" aria-labelledby="addProjectModalLabel" aria-hidden="true">
}
else
{
    @:<div class="modal fade" id="addProjectModal" tabindex="-1" role="dialog" aria-labelledby="addProjectModalLabel" aria-hidden="true">
        }
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="myModalLabel">Add project</h4>
        </div>
        @using (Html.BeginForm("AddOrEditProject", "ProjectList", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(m => m.ProjectId)
            <div class="modal-body">
                <div class="form-group">
                    <label class="control-label col-sm-4" for="email">@Html.LabelFor(x => x.ProjectName):</label>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(x => x.ProjectName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.ProjectName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-4" for="email">@Html.LabelFor(x => x.ProjectShortName):</label>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(x => x.ProjectShortName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.ProjectShortName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-4" for="email">@Html.LabelFor(x => x.ProjectDescription):</label>
                    <div class="col-sm-8">
                        @Html.TextAreaFor(x => x.ProjectDescription, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.ProjectDescription, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        }
    </div>
</div>
</div>



    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

GameAssistantWeb.Main/Views/ProjectList/_DeleteProjectPartial.cshtml
@model GameAssistantWeb.ViewModels.Project.ProjectViewModel
<div class="modal fade" id="deleteProjectModal-@Model.ProjectId" tabindex="-1" role="dialog" aria-labelledby="deleteProjectModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Delete project</h4>
            </div>
            @using (Html.BeginForm("DeleteProject", "ProjectList", FormMethod.Post, new { @class = "form-horizontal" }))
            {
                @Html.HiddenFor(m => m.ProjectId)
                <div class="modal-body">
                    Do you want to delete project? Operation is irreversible and you will lose all data about project (logs, events, users etc.)
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Delete</button>
                </div>
            }
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}