GameAssistantWeb.Main/Controllers/ProjectController.cs
using GameAssistantWeb.DataAccessLayer.Contracts;
using GameAssistantWeb.BusinessLogic.Contracts;
using GameAssistantWeb.Models.Identity;
using GameAssistantWeb.Repository.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameAssistantWeb.ViewModels.Project;

namespace GameAssistantWeb.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        private readonly IUnitOfWork _uow;
        private readonly IAccountService _accountService;
        private readonly IProjectService _projectService;
        private readonly ILevelService _levelService;
        private readonly IEventService _eventService;
        private readonly IAchievementService _achievementService;

        public ProjectController(IUnitOfWork uow, IRepository<ApplicationUser> applicationUserRepository, IAchievementService achievementService, IEventService eventService, ILevelService levelService, IProjectService projectService, IAccountService accountService)
        {
            _uow = uow;
            _accountService = accountService;
            _achievementService = achievementService;
            _projectService = projectService;
            _levelService = levelService;
            _eventService = eventService;
        }


        [HttpGet]
        public ActionResult Index(int ProjectId)
        {
            if (ShouldRedirect(ProjectId))
                return RedirectToAction("Index", "Home");

            return View();
        }


        [HttpGet]
        public ActionResult Levels(int ProjectId)
        {
            if (ShouldRedirect(ProjectId))
                return RedirectToAction("Index", "Home");

            IEnumerable<LevelViewModel> levels = _levelService.GetLevels(ProjectId);

            return View(levels);
        }

        [HttpGet]
        public PartialViewResult _AddLevelPartial(int ProjectId)
        {
            LevelViewModel model = new LevelViewModel { ProjectId = ProjectId };
            return PartialView("_AddOrEditLevelPartial", model);
        }

        [HttpGet]
        public PartialViewResult _EditLevelPartial(int ProjectId, int LevelId)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            LevelViewModel model = _levelService.GetLevel(LevelId);

            if (model.Project.OwnerId != user.Id)
                model = new LevelViewModel();

            return PartialView("_AddOrEditLevelPartial", model);
        }

        [HttpPost]
        public ActionResult AddOrEditLevel(LevelViewModel model)
        {
            if (ShouldRedirect(model.ProjectId))
                return RedirectToAction("Index", "Home");

            var user = _accountService.GetUserByName(User.Identity.Name);

            if (model.LevelId == 0){
                _levelService.AddLevel(model, user.Id);
                TempData["message"] = "Level successfully added";
            }
            else { 
                _levelService.EditLevel(model, user.Id);
                TempData["message"] = "Level successfully edited";
            }

            return RedirectToAction("Levels", new { ProjectId = model.ProjectId });
        }

        [HttpGet]
        public PartialViewResult _DeleteLevelPartial(int LevelId)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            LevelViewModel model = _levelService.GetLevel(LevelId);

            if (model.Project.OwnerId != user.Id)
                model = new LevelViewModel();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult DeleteLevel(LevelViewModel model)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            _levelService.DeleteLevel(model.LevelId, user.Id);

            TempData["message"] = "Level successfully deleted";
            return RedirectToAction("Levels", new { ProjectId = model.ProjectId });
        }








        [HttpGet]
        public ActionResult Events(int ProjectId)
        {
            if (ShouldRedirect(ProjectId))
                return RedirectToAction("Index", "Home");

            IEnumerable<EventViewModel> events = _eventService.GetEvents(ProjectId);

            return View(events);
        }

        [HttpGet]
        public PartialViewResult _AddEventPartial(int ProjectId)
        {
            EventViewModel model = new EventViewModel { ProjectId = ProjectId };
            return PartialView("_AddOrEditEventPartial", model);
        }

        [HttpGet]
        public PartialViewResult _EditEventPartial(int ProjectId, int EventId)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            EventViewModel model = _eventService.GetEvent(EventId);

            if (model.Project.OwnerId != user.Id)
                model = new EventViewModel();

            return PartialView("_AddOrEditEventPartial", model);
        }

        [HttpPost]
        public ActionResult AddOrEditEvent(EventViewModel model)
        {
            if (ShouldRedirect(model.ProjectId))
                return RedirectToAction("Index", "Home");

            var user = _accountService.GetUserByName(User.Identity.Name);

            if (model.EventId == 0)
            {
                _eventService.AddEvent(model, user.Id);
                TempData["message"] = "Event successfully added";
            }
            else
            {
                _eventService.EditEvent(model, user.Id);
                TempData["message"] = "Event successfully edited";
            }

            return RedirectToAction("Events", new { ProjectId = model.ProjectId });
        }

        [HttpGet]
        public PartialViewResult _DeleteEventPartial(int EventId)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            EventViewModel model = _eventService.GetEvent(EventId);

            if (model.Project.OwnerId != user.Id)
                model = new EventViewModel();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult DeleteEvent(EventViewModel model)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            _eventService.DeleteEvent(model.EventId, user.Id);

            TempData["message"] = "Event successfully deleted";
            return RedirectToAction("Events", new { ProjectId = model.ProjectId });
        }





        [HttpGet]
        public ActionResult Achievements(int ProjectId)
        {
            if (ShouldRedirect(ProjectId))
                return RedirectToAction("Index", "Home");

            IEnumerable<AchievementViewModel> events = _achievementService.GetAchievements(ProjectId);

            return View(events);
        }


        [HttpGet]
        public PartialViewResult _AddAchievementPartial(int ProjectId)
        {
            AchievementViewModel model = _achievementService.CreateAchievementViewModel(ProjectId);
            return PartialView("_AddOrEditAchievementPartial", model);
        }


        [HttpGet]
        public PartialViewResult _EditAchievementPartial(int ProjectId, int AchievementId)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            AchievementViewModel model = _achievementService.GetAchievement(AchievementId, ProjectId);

            if (model.Project.OwnerId != user.Id)
                model = _achievementService.CreateAchievementViewModel(ProjectId);

            return PartialView("_AddOrEditAchievementPartial", model);
        }


        [HttpPost]
        public ActionResult AddOrEditAchievement(AchievementViewModel model)
        {
            if (ShouldRedirect(model.ProjectId))
                return RedirectToAction("Index", "Home");

            var user = _accountService.GetUserByName(User.Identity.Name);

            if (model.AchievementId == 0)
            {
                _achievementService.AddAchievement(model, user.Id);
                TempData["message"] = "Event successfully added";
            }
            else
            {
                _achievementService.EditAchievement(model, user.Id);
                TempData["message"] = "Event successfully edited";
            }

            return RedirectToAction("Achievements", new { ProjectId = model.ProjectId });
        }

        [HttpGet]
        public PartialViewResult _DeleteAchievementPartial(int AchievementId)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            AchievementViewModel model = _achievementService.GetAchievement(AchievementId);

            if (model.Project.OwnerId != user.Id)
                model = new AchievementViewModel();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult DeleteAchievement(AchievementViewModel model)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            _achievementService.DeleteAchievement(model.AchievementId, user.Id);

            TempData["message"] = "Achievement successfully deleted";
            return RedirectToAction("Achievements", new { ProjectId = model.ProjectId });
        }

        public bool ShouldRedirect(int ProjectId)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            var project = _projectService.GetProjectById(ProjectId, user.Id);
            if (project == null)
                return true;
            else
            {
                ViewBag.ProjectName = project.ProjectName;
                ViewBag.ProjectId = project.ProjectId;
                return false;
            }
        }
    }
}

GameAssistantWeb.Main/Controllers/ProjectStatisticController.cs
using GameAssistantWeb.DataAccessLayer.Contracts;
using GameAssistantWeb.BusinessLogic.Contracts;
using GameAssistantWeb.Models.Identity;
using GameAssistantWeb.Repository.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameAssistantWeb.ViewModels.Project;
using GameAssistantWeb.Models.Logs;
using GameAssistantWeb.ViewModels.Logs;

namespace GameAssistantWeb.Controllers
{
    public class ProjectStatisticController : Controller
    {

        private readonly IUnitOfWork _uow;
        private readonly IAccountService _accountService;
        private readonly IEventService _eventService;
        private readonly IAchievementService _achievementService;
        private readonly IProjectService _projectService;
        private readonly IUserLogsService _userLogsService;

        public ProjectStatisticController(IUnitOfWork uow, IUserLogsService userLogsService, IAchievementService achievementService, IEventService eventService, IProjectService projectService, IAccountService accountService)
        {
            _uow = uow;
            _accountService = accountService;
            _userLogsService = userLogsService;
            _achievementService = achievementService;
            _eventService = eventService;
            _projectService = projectService;
        }


        [HttpGet]
        public ActionResult Index(int ProjectId)
        {
            if (ShouldRedirect(ProjectId))
                return RedirectToAction("Index", "Home");

            IEnumerable<User> usersStatistic = _userLogsService.GetUsers(ProjectId);
            return View(usersStatistic);
        }


        [HttpPost]
        public ActionResult Index(int ProjectId, DateTime? fromDateTimePicker, DateTime? toDateTimePicker)
        {
            if (ShouldRedirect(ProjectId))
                return RedirectToAction("Index", "Home");

            IEnumerable<User> usersStatistic = _userLogsService.GetUsers(ProjectId);
            if (fromDateTimePicker.HasValue && toDateTimePicker.HasValue)
            {
                foreach (var user in usersStatistic)
                {
                    user.AchievedEvents = user.AchievedEvents.Where(x => x.AchieveDate > fromDateTimePicker && x.AchieveDate < toDateTimePicker).ToList();
                    user.AchievedAchievements = user.AchievedAchievements.Where(x => x.AchieveDate > fromDateTimePicker && x.AchieveDate < toDateTimePicker).ToList();
                    user.Points = 0;
                    foreach (var item in user.AchievedAchievements)
                    {
                        user.Points = user.Points + item.PointsAchieved;
                    }
                    foreach (var item in user.AchievedEvents)
                    {
                        user.Points = user.Points + item.PointsAchieved;
                    }
                }
            }
            return View(usersStatistic);
        }


        public ActionResult Users(int ProjectId)
        {
            if (ShouldRedirect(ProjectId))
                return RedirectToAction("Index", "Home");

            IEnumerable<User> usersStatistic = _userLogsService.GetUsers(ProjectId);
            return View(usersStatistic);
        }

        [HttpGet]
        public ActionResult Events(int ProjectId)
        {
            if (ShouldRedirect(ProjectId))
                return RedirectToAction("Index", "Home");

            IEnumerable<EventViewModel> events = _eventService.GetEvents(ProjectId);

            return View(events);
        }

        [HttpGet]
        public ActionResult Achievements(int ProjectId)
        {
            if (ShouldRedirect(ProjectId))
                return RedirectToAction("Index", "Home");

            IEnumerable<AchievementViewModel> events = _achievementService.GetAchievements(ProjectId);

            return View(events);
        }

        [HttpGet]
        public ActionResult Activity(int ProjectId)
        {
            if (ShouldRedirect(ProjectId))
                return RedirectToAction("Index", "Home");

            IEnumerable<UserActivity> events = _userLogsService.GetUsersActivity(ProjectId);

            return View(events);
        }


        [HttpGet]
        public PartialViewResult _DeleteUserPartial(int UserId)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            User model = _userLogsService.GetUser(UserId);

            if (model.Project.OwnerId != user.Id)
                model = new User();

            return PartialView(model);
        }

        [HttpPost]
        public ActionResult DeleteUser(User model)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            _userLogsService.DeleteUser(model.UserId, user.Id);

            TempData["message"] = "User successfully deleted";
            return RedirectToAction("Users", new { ProjectId = model.ProjectId });
        }



        [HttpGet]
        public PartialViewResult _AdditionalUserDataPartial(int UserId)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            User model = _userLogsService.GetUser(UserId);

            if (model.Project.OwnerId != user.Id)
                model = new User();

            return PartialView(model);
        }



        public bool ShouldRedirect(int ProjectId)
        {
            var user = _accountService.GetUserByName(User.Identity.Name);
            var project = _projectService.GetProjectById(ProjectId, user.Id);
            if (project == null)
                return true;
            else
            {
                ViewBag.ProjectName = project.ProjectName;
                ViewBag.ProjectId = project.ProjectId;
                return false;
            }
        }
    }
}

GameAssistantWeb.Main/Views/Project/Achievements.cshtml
@model IEnumerable<GameAssistantWeb.ViewModels.Project.AchievementViewModel>
@{
    ViewBag.Title = "Achievements";
    Layout = "~/Views/Shared/_ProjectLayout.cshtml";
}

<div class="col-sm-3 col-md-2 sidebar">
    <ul class="nav nav-sidebar">
        <li><a href="@Url.Action("Index","Project", new { ProjectId = ViewBag.ProjectId })">Overview</a></li>
        <li><a href="@Url.Action("Levels", "Project", new { ProjectId = ViewBag.ProjectId })">Levels</a></li>
        <li><a href="@Url.Action("Events", "Project", new { ProjectId = ViewBag.ProjectId })">Events</a></li>
        <li class="active"><a href="@Url.Action("Achievements", "Project", new { ProjectId = ViewBag.ProjectId })">Achievements</a></li>
    </ul>
    <hr />
    <ul class="nav nav-sidebar">
        <li><a href="@Url.Action("Index", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">Main table</a></li>
        <li><a href="@Url.Action("Users", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">Users</a></li>
        <li><a href="@Url.Action("Events","ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">Events statistic</a></li>
        <li><a href="@Url.Action("Achievements", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">Achievement statistic</a></li>
        <li><a href="@Url.Action("Activity", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">User activity</a></li>
    </ul>
</div>



<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h1 class="page-header">Achievements</h1>


    <h2 class="sub-header">Achievement list</h2>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Achievement title</th>
                    <th>Achievement type</th>
                    <th>Connected event</th>
                    <th>Points</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.AchievementId</td>
                        <td>@item.Title</td>
                        <td>@item.AchievementType</td>
                        @if (item.Event != null)
                        {
                            <td>[@item.Event.EventId]@item.Event.Title</td>
                        }
                        else
                        {
                            <td>Not connected to event</td>
                        }
                        <td>@item.PointsForAchieve</td>
                        <td>
                            <i class="glyphicon glyphicon-pencil btn btn-default" title="Edit" data-toggle="modal" data-target="#addAchievementModal-@item.AchievementId"></i>
                            @{Html.RenderAction("_EditAchievementPartial", new { AchievementId = item.AchievementId });}
                        </td>
                        <td>
                            <i class="glyphicon glyphicon-remove btn btn-default" title="Delete" data-toggle="modal" data-target="#deleteAchievementModal-@item.AchievementId"></i>
                            @{Html.RenderAction("_DeleteAchievementPartial", new { AchievementId = item.AchievementId });}
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
    <h2 class="sub-header">Add new achievement</h2>
    <div class="">
        <button type="button" class="btn btn-default  btn-lg" data-toggle="modal" data-target="#addAchievementModal">Add</button>
        @{Html.RenderAction("_AddAchievementPartial", new { AchievementId = ViewBag.AchievementId });}
    </div>

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GameAssistantWeb.Main/Views/Project/Events.cshtml
@model IEnumerable<GameAssistantWeb.ViewModels.Project.EventViewModel>
@{
    ViewBag.Title = "Events";
    Layout = "~/Views/Shared/_ProjectLayout.cshtml";
}

<div class="col-sm-3 col-md-2 sidebar">
    <ul class="nav nav-sidebar">
        <li><a href="@Url.Action("Index","Project", new { ProjectId = ViewBag.ProjectId })">Overview</a></li>
        <li><a href="@Url.Action("Levels", "Project", new { ProjectId = ViewBag.ProjectId })">Levels</a></li>
        <li class="active"><a href="@Url.Action("Events", "Project", new { ProjectId = ViewBag.ProjectId })">Events</a></li>
        <li><a href="@Url.Action("Achievements", "Project", new { ProjectId = ViewBag.ProjectId })">Achievements</a></li>
    </ul>
    <hr />
    <ul class="nav nav-sidebar">
        <li><a href="@Url.Action("Index", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">Main table</a></li>
        <li><a href="@Url.Action("Users", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">Users</a></li>
        <li><a href="@Url.Action("Events","ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">Events statistic</a></li>
        <li><a href="@Url.Action("Achievements", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">Achievement statistic</a></li>
        <li><a href="@Url.Action("Activity", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">User activity</a></li>
    </ul>
</div>



<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h1 class="page-header">Events</h1>


    <h2 class="sub-header">Events list</h2>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Event title</th>
                    <th>Event description</th>
                    <th>Points</th>
                    <th>Multiple event</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.EventId</td>
                        <td>@item.Title</td>
                        <td>@item.Description</td>
                        <td>@item.PointsForAchieve</td>
                        <td>@item.MultipleEvent</td>
                        <td>
                            <i class="glyphicon glyphicon-pencil btn btn-default" title="Edit" data-toggle="modal" data-target="#addEventModal-@item.EventId"></i>
                            @{Html.RenderAction("_EditEventPartial", new { EventId = item.EventId });}
                        </td>
                        <td>
                            <i class="glyphicon glyphicon-remove btn btn-default" title="Delete" data-toggle="modal" data-target="#deleteEventModal-@item.EventId"></i>
                            @{Html.RenderAction("_DeleteEventPartial", new { EventId = item.EventId });}
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
    <h2 class="sub-header">Add new event</h2>
    <div class="">
        <button type="button" class="btn btn-default  btn-lg" data-toggle="modal" data-target="#addEventModal">Add</button>
        @{Html.RenderAction("_AddEventPartial", new { ProjectId = ViewBag.ProjectId });}
    </div>

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GameAssistantWeb.Main/Views/Project/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ProjectLayout.cshtml";
}

<div class="col-sm-3 col-md-2 sidebar">
    <ul class="nav nav-sidebar">
        <li class="active"><a href="@Url.Action("Index", "Project", new { ProjectId = ViewBag.ProjectId })">Overview</a></li>
        <li><a href="@Url.Action("Levels","Project", new { ProjectId = ViewBag.ProjectId })">Levels</a></li>
        <li><a href="@Url.Action("Events", "Project", new { ProjectId = ViewBag.ProjectId })">Events</a></li>
        <li><a href="@Url.Action("Achievements", "Project", new { ProjectId = ViewBag.ProjectId })">Achievements</a></li>
    </ul>
    <hr />
    <ul class="nav nav-sidebar">
        <li><a href="@Url.Action("Index", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">Main table</a></li>
        <li><a href="@Url.Action("Users", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">Users</a></li>
        <li><a href="@Url.Action("Events","ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">Events statistic</a></li>
        <li><a href="@Url.Action("Achievements", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">Achievement statistic</a></li>
        <li><a href="@Url.Action("Activity", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">User activity</a></li>
    </ul>
</div>



<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h1 class="page-header">Dashboard</h1>

    <h2 class="sub-header">Documentation</h2>
    <div class="row">

        <div class="col-md-4">
            <h2>Documentation and API</h2>
            <p>Here you will find our documentation and API description.</p>
            <p><a class="btn btn-default" href="@Url.Action("Documentation", "Home")">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Examples</h2>
            <p>Examples of implementation and some showcases of usage our system. What is more - information about system: modules, parts etc. </p>
            <p><a class="btn btn-default" href="@Url.Action("Examples", "Home")">Show me &raquo;</a></p>
        </div>
    </div>
    <hr />
    <h2 class="sub-header">Project configuration</h2>
    <div class="row">

        <div class="col-md-4">
            <h2>Events (Points)</h2>
            <p>Manage events module.</p>
            <p><a class="btn btn-default" href="@Url.Action("Events", "Project", new { ProjectId = ViewBag.ProjectId })">Manage &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Levels</h2>
            <p>Manage levels module.</p>
            <p><a class="btn btn-default" href="@Url.Action("Events", "Project", new { ProjectId = ViewBag.ProjectId })">Manage &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Achievements (Goals)</h2>
            <p>Manage achievements module.</p>
            <p><a class="btn btn-default" href="@Url.Action("Events", "Project", new { ProjectId = ViewBag.ProjectId })">Manage &raquo;</a></p>
        </div>
    </div>
    <hr />
    <h2 class="sub-header">Project statistic</h2>
    <div class="row">

        <div class="col-md-3">
            <h2>Main table</h2>
            <p>User leaderboard in diffrent time approach.</p>
            <p><a class="btn btn-default" href="@Url.Action("Index", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId }))">Manage &raquo;</a></p>
        </div>
        <div class="col-md-3">
            <h2>Events activity</h2>
            <p>Show events activity.</p>
            <p><a class="btn btn-default" href="@Url.Action("Events", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId }))">Manage &raquo;</a></p>
        </div>
        <div class="col-md-3">
            <h2>Achievements activity</h2>
            <p>Show achievements activity.</p>
            <p><a class="btn btn-default" href="@Url.Action("Achievements", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId }))">Manage &raquo;</a></p>
        </div>
        <div class="col-md-3">
            <h2>User activity</h2>
            <p>Show users activity.</p>
            <p><a class="btn btn-default" href="@Url.Action("Activity", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId }))">Manage &raquo;</a></p>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GameAssistantWeb.Main/Views/Project/Levels.cshtml
@model IEnumerable<GameAssistantWeb.ViewModels.Project.LevelViewModel>
@{
    ViewBag.Title = "Levels";
    Layout = "~/Views/Shared/_ProjectLayout.cshtml";
}

<div class="col-sm-3 col-md-2 sidebar">
    <ul class="nav nav-sidebar">
        <li><a href="@Url.Action("Index","Project", new { ProjectId = ViewBag.ProjectId })">Overview</a></li>
        <li class="active"><a href="@Url.Action("Levels", "Project", new { ProjectId = ViewBag.ProjectId })">Levels</a></li>
        <li><a href="@Url.Action("Events", "Project", new { ProjectId = ViewBag.ProjectId })">Events</a></li>
        <li><a href="@Url.Action("Achievements", "Project", new { ProjectId = ViewBag.ProjectId })">Achievements</a></li>
    </ul>
    <hr />
    <ul class="nav nav-sidebar">
        <li><a href="@Url.Action("Index", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">Main table</a></li>
        <li><a href="@Url.Action("Users", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">Users</a></li>
        <li><a href="@Url.Action("Events", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">Events statistic</a></li>
        <li><a href="@Url.Action("Achievements","ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">Achievement statistic</a></li>
        <li><a href="@Url.Action("Activity", "ProjectStatistic", new { ProjectId = ViewBag.ProjectId })">User activity</a></li>
    </ul>
</div>



<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
    <h1 class="page-header">Levels</h1>


    <h2 class="sub-header">Levels list</h2>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Level name</th>
                    <th>Lower threshold</th>
                    <th>Upper threshold</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.LevelTitle</td>
                        <td>@item.LowerThreshold</td>
                        @if (!item.UpperThresholdInf)
                        {
                            <td>@item.UpperThreshold</td>
                        }
                        else
                        {
                            <td>inf</td>
                        }

                        <td>
                            <i class="glyphicon glyphicon-pencil btn btn-default" title="Edit" data-toggle="modal" data-target="#addLevelModal-@item.LevelId"></i>
                            @{Html.RenderAction("_EditLevelPartial", new { LevelId = item.LevelId });}
                        </td>
                        <td>
                            <i class="glyphicon glyphicon-remove btn btn-default" title="Delete" data-toggle="modal" data-target="#deleteLevelModal-@item.LevelId"></i>
                            @{Html.RenderAction("_DeleteLevelPartial", new { LevelId = item.LevelId });}
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    </div>
    <h2 class="sub-header">Add new level</h2>
    <div class="">
        <button type="button" class="btn btn-default  btn-lg" data-toggle="modal" data-target="#addLevelModal">Add</button>
        @{Html.RenderAction("_AddLevelPartial", new { ProjectId = ViewBag.ProjectId });}
    </div>

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}